import { ProductProvider } from "@/context/ProductContext";
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import Script from "next/script";
import ClientLayout from "@/components/ClientLayout";
import { AuthProvider } from "@/context/authContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <AuthProvider>
          <ClientLayout>{children}</ClientLayout>{" "}
        </AuthProvider>
        {/* اینجا از کامپوننت کلاینتی استفاده می‌کنیم */}
        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></Script>
      </body>
    </html>
  );
}
